[package]
name = "camilladsp"
version = "0.0.11"
authors = ["Henrik Enquist <henrik.enquist@gmail.com>"]
description = "A flexible tool for processing audio"

[features]
default = ["alsa-backend", "pulse-backend", "socketserver"]
alsa-backend = ["alsa"]
pulse-backend = ["libpulse-simple-binding", "libpulse-binding"]
32bit = []
socketserver = ["ws"]
FFTW = ["fftw"]

[dependencies]
alsa = { version = "0.4", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
rustfft = "3.0.0"
fftw = { version = "0.6.0", optional = true }
num-traits = "0.2"
num = "0.2"
itertools = "0.9.0"
signal-hook = "0.1.13"
rand = "0.7.3"
rand_distr = "0.2.2"
clap = "2.33.0"
log = "0.4.8"
env_logger = "0.7.1"
ws = { version = "0.9.1", optional = true }
libpulse-binding = { version = "2.0", optional = true }
libpulse-simple-binding = { version = "2.0", optional = true }
